# Generated by Django 6.0 on 2025-12-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_created_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sticks', 'Incense Sticks'), ('cones', 'Dhoop Cones'), ('dhoop', 'Dhoop Sticks')], default='sticks', max_length=20),
            preserve_default=False,
        ),
    ]
