# Generated by Django 6.0 on 2025-12-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sticks', 'Incense Sticks'), ('cones', 'Dhoop Cones'), ('dhoop', 'Dhoop Sticks'), ('combo', 'Combo Pack')], max_length=20),
        ),
    ]
