# Generated by Django 6.0 on 2025-12-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sticks', 'Incense Sticks'), ('cones', 'Dhoop Cones'), ('dhoop', 'Dhoop Sticks'), ('combo', 'Combo Pack'), ('hamper', 'Hamper')], max_length=20),
        ),
    ]
