# Generated by Django 6.0 on 2026-01-08 15:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='timezone.now', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
